############# English navigation ##############

# main menu
[[main]]
name = "主页"
url = "/"
weight = 1

[[main]]
name = "知识库"
url = "/knowledges"
weight = 2

[[main]]
name = "关于"
url = "/about"
weight = 3


# footer menu
[[footer]]
name = "关于"
url = "/about"
weight = 1

[[footer]]
name = "隐私政策"
url = "/privacy-policy"
weight = 2
